from os.path import dirname, join; 
DIR = join(dirname(__file__), '..')
DATA = join(DIR, 'data')


GROUND_FRICTION = 1.5
LANDER_FUEL = 1000
LANDER_LEG_STRENGTH = 10
LANDER_THRUST = 40
LANDER_SIDE_THRUST = 10
# Inverted
MOMENTUM_SENSITIVITY = 1 # was 10
ROTATION_SENSITIVITY = 1 # was 2
# Inverted
GRAVITY_SENSITIVITY  = 5 # was 100
FUEL_WEIGHT = .2
FUEL_THRUST = 5
LANDER_WEIGHT = 100
BASE_ROTATION_SPEED = 200
# Inverted
MOMENTUM_FIRE_ADJUST = 1

LANDER_THRUST *= FUEL_THRUST
LANDER_SIDE_THRUST *= FUEL_THRUST

THRUSTER_FUEL_USAGE_MULTIPLIER = .02

KEY_REPEAT_DELAY = 20
KEY_REPEAT_INTERVAL = 20
FPS = 30
START_FULLSCREEN = False
GRAVITY = 1.6 # Moon's gravity
# GRAVITY = 1
GROUND_COLOR = [200, 200, 200]
GROUND_START_Y = 200
EXPLODE_TIME = 35
GROUND_X_WIDTH = 1
SCROLL_WIDTH = 200
SLOPE = 26
FLATTNESS = 100
ITEM_FLOAT_HEIGHT = 10

# Inverted
GAS_CAN_SPAWN_CHANCE   = 1
MIN_GAS_CAN_SPAWN_DIST = 1379
MAX_GAS_CAN_SPAWN_DIST = 100

# Inverted
COIN_SPAWN_CHANCE      = 50
MIN_COIN_SPAWN_DIST    = 50
MAX_COIN_SPAWN_DIST    = 500
COIN_WORTH = 1

# Inverted
SUPER_COIN_SPAWN_CHANCE   = 20
MIN_SUPER_COIN_SPAWN_DIST = 50
SUPER_COIN_WORTH = 100

ITEM_GENERATE_MORE_IGNORE_AMOUNT = 50



# MIN_GAS_CAN_SPAWN_DIST *= ITEM_GENERATE_MORE_IGNORE_AMOUNT
# MAX_GAS_CAN_SPAWN_DIST *= ITEM_GENERATE_MORE_IGNORE_AMOUNT
# MIN_COIN_SPAWN_DIST *= ITEM_GENERATE_MORE_IGNORE_AMOUNT
# MAX_COIN_SPAWN_DIST *= ITEM_GENERATE_MORE_IGNORE_AMOUNT
# MIN_SUPER_COIN_SPAWN_DIST *= ITEM_GENERATE_MORE_IGNORE_AMOUNT
# SUPER_COIN_WORTH *= ITEM_GENERATE_MORE_IGNORE_AMOUNT

GUI_THEME_FILE = DIR + 'data/myTheme.json'

SCROLLING_LEFT  = 2
SCROLLING_RIGHT = 3
NOT_SCROLLING   = 0